# https://github.com/matomo-org/matomo-log-analytics/blob/4.x-dev/import_logs.py
PATTERN_COMMON_LOG_FORMAT = (
    r'(?P<ip>[\w*.:-]+)\s+\S+\s+(?P<userid>\S+)\s+\[(?P<date>.*?)\s+(?P<timezone>.*?)\]\s+'
    r'"(?P<method>\S+)\s+(?P<path>.*?)\s+\S+"\s+(?P<status>\d+)\s+(?P<length>\S+)'
)

# https://github.com/matomo-org/matomo-log-analytics/blob/4.x-dev/import_logs.py
PATTERN_NCSA_EXTENDED_LOG_FORMAT = (
    PATTERN_COMMON_LOG_FORMAT + r'\s+"(?P<referrer>.*?)"\s+"(?P<user_agent>.*?)"'
)

# https://github.com/matomo-org/matomo-log-analytics/blob/4.x-dev/import_logs.py
EXTENSIONS_STATIC = set([
    'gif',
    'jpg',
    'jpeg',
    'png',
    'bmp',
    'ico',
    'svg',
    'svgz',
    'ttf',
    'otf',
    'eot',
    'woff',
    'woff2',
    'class',
    'swf',
    'css',
    'js',
    'xml',
    'webp'
])

# https://github.com/matomo-org/matomo-log-analytics/blob/4.x-dev/import_logs.py
EXTENSIONS_DOWNLOAD = set([
    '7z',
    'aac',
    'arc',
    'arj',
    'asf',
    'asx',
    'avi',
    'bin',
    'csv',
    'deb',
    'dmg',
    'doc',
    'docx',
    'exe',
    'flac',
    'flv',
    'gz',
    'gzip',
    'hqx',
    'ibooks',
    'jar',
    'json',
    'mpg',
    'mp2',
    'mp3',
    'mp4',
    'mpeg',
    'mov',
    'movie',
    'msi',
    'msp',
    'odb',
    'odf',
    'odg',
    'odp',
    'ods',
    'odt',
    'ogg',
    'ogv',
    'pdf',
    'phps',
    'ppt',
    'pptx',
    'qt',
    'qtm',
    'ra',
    'ram',
    'rar',
    'rpm',
    'rtf',
    'sea',
    'sit',
    'tar',
    'tbz',
    'bz2',
    'tbz',
    'tgz',
    'torrent',
    'txt',
    'wav',
    'webm',
    'wma',
    'wmv',
    'wpd',
    'xls',
    'xlsx',
    'xml',
    'xsd',
    'z',
    'zip',
    'azw3',
    'epub',
    'mobi',
    'apk',
    'md5',
    'sig'
])
